### ISSUE TITLE
[Adolescent Sewa Rural]: App Go Live New Form & App Changes May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#101]
**- [ ] Functional**

- [x]  Visit Scheduling Logic: All Forms
- [x]  Over the App flow
- [x]  Operational Reports
- [x]  User Permissions

**- [ ] Data**

- [x]  Users, Location & Catchment Data & Creation
- [x]  User Permissions
- [x]  Void all test data in production
- [x]  Disable UAT users
- [x]  Translation using Lokalise
