### ISSUE TITLE
[Adolescent Sewa Rural]: Go Live: Checklist: For QA & BA

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#109]
- [ ] Visit Schedule Logics
- [ ] Over all App flow
- [ ] Translations (Gujarati)
- [ ] Disable UAT Users
