### ISSUE TITLE
[SR Card 4] Changes for latest Standard to be available in the app

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#24]
## Context
Currently search filter looks for value in the entire enrolment and not on the latest value. Standard/Grade is updated every year in the Baseline form. We want users to have the ability to get the list of the students with latest Standard via Search.

## Tasks

- [x] 1.Update Program enrolment decision to have a new variable - "Current Standard" to store the latest Standard value from the Baseline form ie. whenever a Baseline form is completed, it should update the decision rule to update the enrolment decision "Current Standard" with the latest value filled in.
- [x] 2. Add a search filter on this new enrolment decision concept
- [x] 3. Write a script to update this new enrolment decision concept value from the latest available baseline data for all the existing individuals.

**Comment by adamsanadi6** [comment]
[Script link](https://github.com/avniproject/Adolescent-Sewa-Rural/blob/main/migrations/Query%20to%20update%20current%20standard%20decision.sql)

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 as discussed since there are changes in script and no data on UAT to test, please run updated query on prerelease UAT after uploading latest changes from prod UAT env.

Hence moving card back to ready lane.

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 Looks the relevant changes for this card are present on prerelease ADSR org, you can run the updated script over there and then move it to QA.

Let me know in case you face any challenge in doing it.

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal, I have made the changes as requested in the review. [Here is the ticket link for reference](https://avni.freshdesk.com/a/tickets/3530). 
 I ran the updated query in the prerelease ADSR org
