### ISSUE TITLE
[Adolescent Sewa Rural]: Data Fix - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#57]
> [Analysis](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1855338938)

- [x] Scripts for following cards will be written on ADSR UAT 
- [x] Cards will be moved to review ready and will be reviewed by product team via support ticket
- [x] Once reviewed, run on UAT
- [x] Get the QA done
- [x] Once app changes May 2024 are moved to production
- [x] Run these script on prod with a downtime of 2 hrs
- [x] One round of QA for Sanity testing

**Comment by Dinesh2019** [comment]
card 1 : tested SQL Query

select * from individual i 
left join program_encounter pe on i.id = pe.individual_id 
where pe.encounter_type_id = 3171 and pe.earliest_visit_date_time BETWEEN '2023-04-01' AND '2024-03-31'
and pe.encounter_date_time is null 
and pe.cancel_date_time is  null;
